SRC = ./ft_display_file.c
NAME = ft_display_file
C_FLAGS = -Wall -Wextra -Werror -o
RM = /bin/rm -f

all: $(NAME)

$(NAME):
	gcc $(C_FLAGS) $(SRC) -o $(NAME)

clean:
	$(RM) *.o

fclean: clean
	$(RM) $(NAME)


